project_name: ddns-go

version: 2

builds:
  - id: ddns-go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.buildTime={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
    goamd64: 
      - v3
      - v2
    main: ./cmd/ddns-go
    binary: ddns-go

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Amd64 }}"
    format: tar.gz